require:
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  EnforcedStyle: "never"

Style/StringLiterals:
  ConsistentQuotesInMultiline: true
  EnforcedStyle: "double_quotes"
